export const SELECT_ALL = 'SELECT_ALL';
export const FETCH_SITEMAPS = 'FETCH_SITEMAPS';
export const SELECT_SINGLE = 'SELECT_SINGLE';
export const DELETE_SITEMAP = 'DELETE_SITEMAP';
export const DELETE_SITEMAPS = 'DELETE_SITEMAPS';
export const FILTER_URLS = 'FILTER_URLS';
export const FILTER_STATUS = 'FILTER_STATUS';